name: Rspec

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.6.9
          - 2.7
          - 3.0
          - 3.1
          - 3.2
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          sudo apt-get install -y netcat

      - name: Waiting for MySQL
        run: |
          while ! nc -z 127.0.0.1 3306; do sleep 1; done

      - name: Run RSpec
        run: |
          bundle exec rspec
